; File for adding environment during the nested calls of the script.

[config]
; File for running an executable with the cmake environment.
cmake-run-file=cmake/lib/run-executable.cmake
; Override the default docker image using a smaller one without the QT libraries.
docker-image=nexus.scanframe.com/amd64/gnu-cpp:24.04
;docker-image=avolphen/amd64-gnu-cpp:24.04
;docker-image=amd64/gnu-cpp:24.04

; Sematic versioning type impact map.
[config-ver-type-map]
fix=patch,Bugfix
feat=minor,Feature
build=patch,Build Tool/Process
chore=patch,Chore
ci=patch,CI Configuration
docs=patch,Documentation
style=patch,Code Formatting/Styling
refactor=patch,Code Refactoring
perf=patch,Performance
test=none,Test Addition/Modification
revert=patch,Revert of Commit

; Section for optional include file which is merged.
[__include__]
user=user.ini
nexus=.nexus-credentials.ini

; Environment added when running in Wine natively.
; It needs Python 3.12, CMake 4.2, Ninja 1.13 and NSIS 3.11 which can be installed but also shared through the toolchain directory.
; Windows Git is not completely working since it is using Cygwin libraries and a Git server/client is devised to overcome it.
[env.wine@]
; Convenient variable for common base directory.
TOOL_ROOT=Z:${RUN_DIR}\lib\toolchain\win-x86_64-cmake-4.2-combi
; Configuration for tools as cmake, git and ninja for within the Wine environment.
WINEPATH=${TOOL_ROOT}\cmake\bin;${TOOL_ROOT}\bin;${TOOL_ROOT}\python;${TOOL_ROOT}\nsis
; Alternate port for the git server incase of conflicts.
;GIT_SERVER_PORT=8888
; Alternate Wine prefix directory.
;WINEPREFIX=

; Environment added before running Docker.
[env.docker@]
; Nothing yet.

; Environment added before running with the compiler msvc natively.
[env.msvc@]
SF_EXEC_DIR_SUFFIX=-msvc
; Location of the root of the MSVC toolchain in the Wine environment.
; The rest is environment as below is configured in the file CMakePresets.json to allow multiple compilers to be configured in the same project.
MSVC_ROOT=${RUN_DIR}\lib\toolchain\w64-x86_64-msvc-2022
WINEDEBUG=fixme-all

; Environment added before running with the compiler msvc in Wine.
[env.msvc.wine@]
__inherit__=env.msvc@

; Environment added before running Wine in the Docker container.
[env.wine.docker@]

; Environment added before running with the compiler msvc in Wine in the Docker container.
[env.msvc.wine.docker@]
# The Docker container is build with the MSVC toolchain. (fuse-zip mounted in the home directory).
MSVC_ROOT=Z:\home\${USER}\toolchain\w64-x86_64-msvc-2022
SF_EXEC_DIR_SUFFIX=-msvc

; Environment added when running wine natively to execute the Windows cross-compiled targets.
[env.gw@]
SF_EXEC_DIR_SUFFIX=-gw
WINEPATH=Z:\usr\x86_64-w64-mingw32\lib;Z:\usr\lib\gcc\x86_64-w64-mingw32\13-posix

; Environment added before running the 'mingw' compiler natively.
[env.mingw@]
SF_EXEC_DIR_SUFFIX=-mingw
PATH=${RUN_DIR}\lib\toolchain\w64-x86_64-mingw-1320-posix\bin;${PATH}

[env.mingw.wine@]
__inherit__=env.mingw@

; Environment added before running the 'mingw' compiler in Docker and Wine.
[env.mingw.wine.docker@]
SF_EXEC_DIR_SUFFIX=-mingw
PATH=Z:\home\${USER}\toolchain\w64-x86_64-mingw-1320-posix\bin;lib;${PATH}

; Environment added before running the 'gw' compiler in the Docker container.
[env.gw.docker@]
SF_EXEC_DIR_SUFFIX=-gw
; Provides compiler std libraries to be found.
WINEPATH=Z:\usr\x86_64-w64-mingw32\lib;Z:\usr\lib\gcc\x86_64-w64-mingw32\13-posix;
; Prevent displaying Wine warnings.
WINEDEBUG=fixme-all

