;;
;; Sample ini-profile modify the path PATH environment variable for the application to run.
;; Also providing a way to add arguments to the executable or change the working directory.
;; Paths or directories not starting like with 'C:\' where 'C' is any drive letter are
;; considered relative and need to be resolved. A path like '..\..\app.exe' is to be resolved as well.
;; It also manipulates the environment using the 'ENV@' section.
;;

; Optional flags to use.
[OPTIONS]
; For now only one level and value 1 which prints the actual used ini-sections to stderr.
debug-level=0

; Section to determine the maximum execution time by default and per symlink name.
[MAX-TIME]
; Execution time for all others.
@=0
; Execution time in seconds when the symlink is named 'my-symlink'.
my-symlink=30

; Redirection of the 'PATH@' ini-section per named symlink.
; The symlink named key exists it results ini-section named 'PATH@<value>'.
; In short the found key value is used as a suffix for 'PATH@'.
; When the symlink does not exist the ini section is 'PATH@'.
[MAP@RUN]
; When 'my-symlink' is the used the ini-section is 'PATH@app2'.
ctl-panel=panel
np++=nppluplus

; Redirection of the 'ENV@' ini-section per named symlink.
; The symlink named key exists it results ini-section named 'ENV@<value>'.
; In short the found key value is used as a suffix for 'ENV@'.
; When the symlink does not exist the ini section is 'ENV@'.
[MAP@ENV]
; When 'my-symlink' is the used the ini-section is 'ENV@app2'.
ctl-panel=panel
np++=nppluplus

; Redirection of the 'RUN@' ini-section per named symlink.
; The symlink named key exists it results ini-section named 'RUN@<value>'.
; In short the found key value is used as a suffix for 'RUN@'.
; When the symlink does not exist the ini section used is 'RUN@'.
[MAP@RUN]
; When 'my-symlink' is the used the ini-section is 'RUN@app2'.
ctl-panel=panel
np++=nppluplus

; Path modification section.
[PATH@]
; Optional key with directories are added at the end of the path where
; 'Tools\Bin' is a relative path which is to be resolved.
;prepend=C:\MyApp1;Tools\Bin
; Optional key with directories which are added at the beginning of the path.
;append=C:\MyApp2;C:\MyApp2\Tools
; Optional key with directories to replacing the complete path.
#replace=C:\MyApp3;C:\MyApp3\Tools

; Environment entries section replacing or adding variables.
[ENV@]
; Replaces or adds a environment variable where the key is the
; variable name and the value is the value.
;MY-ENV-VAR1=My Value 1
;MY-ENV-VAR2="My Value 2"
; Create a nice prompt.
PROMPT="$E[33m%USERNAME%@%COMPUTERNAME% $E[32m$P$E[0m$G "

; Application run section where relative directories and the executable
; are resolved as relative to the `cmd-pass.exe` realpath.
[RUN@]
; Optional working directory which could be relative or absolute for the executable to run.
; When not given or empty the current working directory is not changed.
;workdir=
; Optional arguments (space separated) to prepend and pass on to the executable.
;prepend=
; Optional arguments (space separated) to append and pass on to the executable.
;append=
; When present and value zero it hides the console Window or not create it at all if possible.
; Possible API call to: ShowWindow(GetConsoleWindow(), SW_HIDE);
console=1
; Executable path which is relative or absolute.
executable="C:\Windows\System32\cmd.exe"

[RUN@panel]
console=0
executable=C:\Windows\explorer.exe
append=::{21EC2020-3AEA-1069-A2DD-08002B30309D}

[RUN@nppluplus]
console=0
workdir=.
executable="C:\Program Files\Notepad++\notepad++.exe"
